site_name: ThorVision
site_url: https://kontex-neuro.github.io/ThorVision/
site_description: ThorVision Desktop Video Capture GUI App
copyright: Copyright &copy; 2025 <a href="https://www.kontex.io/" target="_blank" rel="noopener">KonteX Neuroscience</a>

repo_name: kontex-neuro/ThorVision
repo_url: https://github.com/kontex-neuro/ThorVision

theme:
  name: material

  features:
    - navigation.tabs
    - navigation.top
    - navigation.instant
    - navigation.instant.progress
    - navigation.indexes
    - navigation.footer
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.code.annotations
    - toc.follow

  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/lightbulb-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      # primary: teal
      # accent: amber
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      # primary: teal
      # accent: amber
      toggle:
        icon: material/lightbulb-outline
        name: Switch to system preference

  icon:
    repo: fontawesome/brands/github
  logo: favicon.png
  favicon: favicon.png

nav:
  - Home: index.md
  # - Getting Started:
  #     - getting-started.md
  #     - Deployment: deployment.md
  - User Manual:
      - user-manual.md
      - XDAQ Metadata: xdaq-metadata.md
      - USB Cameras: usb-cameras.md
      - Camera Latency: camera-latency.md
  - Metadata Processing:
      - metadata-processing.md
  - FAQs: FAQs.md

markdown_extensions:
  - attr_list
  - md_in_html
  - tables
  - pymdownx.superfences
  - pymdownx.blocks.admonition:
      types:
        - note
        - warning
        - tip
        - example
  - pymdownx.highlight
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true

plugins:
  search:
  mkdocstrings:
    default_handler: cxx

extra_css:
  - extra.css
  - https://unpkg.com/katex@0/dist/katex.min.css

extra_javascript:
  - js/katex.js
  - js/mathjax.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/kontex-neuro/ThorVision
